In [ ]:
# LAB 3 - NumPy Operations

# **1.import numpy**

In [ ]:
import numpy as np

# **2.manuplating numpy arrays**

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(arr1)
print(arr2)
print(arr3)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# **3.Indexing and slicing**

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[1:4])

10
[20 30 40]


# **4**.Reshaping

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


# **5**.**Math operations**

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)
print(a+5)

[5 7 9]
[ 4 10 18]
[6 7 8]


# **6**.**Statistics**

In [ ]:
data = np.array([10,20,30,40,50])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.percentile(data,25))

30.0
30.0
14.142135623730951
20.0


# **7**.**Linear Algebra**

In [ ]:
x = np.array([1,2])
y = np.array([3,4])

print(np.dot(x,y))

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.matmul(A,B))

11
[[19 22]
 [43 50]]


# **8.Random Numbers**

In [ ]:
import time

lst = list(range(1000000))

start = time.time()
sum(lst)
print("List:", time.time()-start)

arr = np.array(lst)

start = time.time()
np.sum(arr)
print("NumPy:", time.time()-start)

List: 0.008999347686767578
NumPy: 0.0006890296936035156
